//@version=6
strategy(
    title="Gaussian Channel Stocks Trend Radar - Green/Red Flip Strategy",
    overlay=true,
    calc_on_every_tick=false,
    initial_capital=1000,
    default_qty_type=strategy.percent_of_equity,
    default_qty_value=95,
    commission_type=strategy.commission.percent,
    commission_value=0.1,
    slippage=3,
    fill_orders_on_standard_ohlc=true,
    margin_long=100,
    margin_short=100
)

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// Date condition inputs
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
startDate = input.time(timestamp("1 January 2018 00:00 +0000"), "Start Date", group="Main Algo Settings")
endDate = input.time(timestamp("31 Dec 2069 23:59 +0000"), "End Date", group="Main Algo Settings")
timeCondition = time >= startDate and time <= endDate

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// Gaussian Channel Indicator - courtesy of @DonovanWall
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------

// Source
src = input(defval=hlc3, title="Source")

// Poles
int N = input.int(defval=4, title="Poles", minval=1, maxval=9)

// Period
int per = input.int(defval=144, title="Sampling Period", minval=2)

// True Range Multiplier
float mult = input.float(defval=1.414, title="Filtered True Range Multiplier", minval=0)

// Lag Reduction
bool modeLag  = input.bool(defval=false, title="Reduced Lag Mode")
bool modeFast = input.bool(defval=false, title="Fast Response Mode")

// Functions for Gaussian filter
f_filt9x (_a, _s, _i) =>
    int _m2 = 0, int _m3 = 0, int _m4 = 0, int _m5 = 0, int _m6 = 0, int _m7 = 0, int _m8 = 0, int _m9 = 0, float _f = .0, _x = (1 - _a)
    _m2 := _i == 9 ? 36  : _i == 8 ? 28 : _i == 7 ? 21 : _i == 6 ? 15 : _i == 5 ? 10 : _i == 4 ? 6 : _i == 3 ? 3 : _i == 2 ? 1 : 0
    _m3 := _i == 9 ? 84  : _i == 8 ? 56 : _i == 7 ? 35 : _i == 6 ? 20 : _i == 5 ? 10 : _i == 4 ? 4 : _i == 3 ? 1 : 0
    _m4 := _i == 9 ? 126 : _i == 8 ? 70 : _i == 7 ? 35 : _i == 6 ? 15 : _i == 5 ? 5  : _i == 4 ? 1 : 0
    _m5 := _i == 9 ? 126 : _i == 8 ? 56 : _i == 7 ? 21 : _i == 6 ? 6  : _i == 5 ? 1  : 0
    _m6 := _i == 9 ? 84  : _i == 8 ? 28 : _i == 7 ? 7  : _i == 6 ? 1  : 0
    _m7 := _i == 9 ? 36  : _i == 8 ? 8  : _i == 7 ? 1  : 0
    _m8 := _i == 9 ? 9   : _i == 8 ? 1  : 0
    _m9 := _i == 9 ? 1   : 0
    _f :=   math.pow(_a, _i)*nz(_s) 
          + _i*_x*nz(_f[1]) 
          - (_i >= 2 ? _m2*math.pow(_x, 2)*nz(_f[2]) : 0) 
          + (_i >= 3 ? _m3*math.pow(_x, 3)*nz(_f[3]) : 0) 
          - (_i >= 4 ? _m4*math.pow(_x, 4)*nz(_f[4]) : 0) 
          + (_i >= 5 ? _m5*math.pow(_x, 5)*nz(_f[5]) : 0) 
          - (_i >= 6 ? _m6*math.pow(_x, 6)*nz(_f[6]) : 0) 
          + (_i >= 7 ? _m7*math.pow(_x, 7)*nz(_f[7]) : 0) 
          - (_i >= 8 ? _m8*math.pow(_x, 8)*nz(_f[8]) : 0) 
          + (_i == 9 ? _m9*math.pow(_x, 9)*nz(_f[9]) : 0)

f_pole (_a, _s, _i) =>
    _f1 = f_filt9x(_a, _s, 1)
    _f2 = _i >= 2 ? f_filt9x(_a, _s, 2) : 0
    _f3 = _i >= 3 ? f_filt9x(_a, _s, 3) : 0
    _f4 = _i >= 4 ? f_filt9x(_a, _s, 4) : 0
    _f5 = _i >= 5 ? f_filt9x(_a, _s, 5) : 0
    _f6 = _i >= 6 ? f_filt9x(_a, _s, 6) : 0
    _f7 = _i >= 7 ? f_filt9x(_a, _s, 7) : 0
    _f8 = _i >= 8 ? f_filt9x(_a, _s, 8) : 0
    _f9 = _i == 9 ? f_filt9x(_a, _s, 9) : 0
    _fn = _i == 1 ? _f1 : _i == 2 ? _f2 : _i == 3 ? _f3 :
          _i == 4 ? _f4 : _i == 5 ? _f5 : _i == 6 ? _f6 :
          _i == 7 ? _f7 : _i == 8 ? _f8 : _i == 9 ? _f9 : na
    [_fn, _f1]

// Beta and Alpha
beta  = (1 - math.cos(4*math.asin(1)/per)) / (math.pow(1.414, 2/N) - 1)
alpha = -beta + math.sqrt(math.pow(beta, 2) + 2*beta)

// Lag
lag = (per - 1)/(2*N)

// Data
srcdata = modeLag ? src + (src - src[lag]) : src
trdata  = modeLag ? ta.tr(true) + (ta.tr(true) - ta.tr(true)[lag]) : ta.tr(true)

// Filtered Values
[filtn, filt1]     = f_pole(alpha, srcdata, N)
[filtntr, filt1tr] = f_pole(alpha, trdata,  N)

// Lag Reduction
filt   = modeFast ? (filtn + filt1)/2 : filtn
filttr = modeFast ? (filtntr + filt1tr)/2 : filtntr

// Bands
hband = filt + filttr*mult
lband = filt - filttr*mult

// Colors
fcolor   = filt > filt[1] ? #0aff68 : filt < filt[1] ? #ff0a5a : #cccccc
barcolor = (src > src[1]) and (src > filt) and (src < hband) ? #0aff68 : 
           (src > src[1]) and (src >= hband) ? #0aff1b : 
           (src <= src[1]) and (src > filt) ? #00752d : 
           (src < src[1]) and (src < filt) and (src > lband) ? #ff0a5a : 
           (src < src[1]) and (src <= lband) ? #ff0a11 : 
           (src >= src[1]) and (src < filt) ? #990032 : #cccccc

// Outputs
filtplot = plot(filt, title="Filter", color=fcolor, linewidth=3)
hbandplot = plot(hband, title="Filtered True Range High Band", color=fcolor)
lbandplot = plot(lband, title="Filtered True Range Low Band", color=fcolor)
fill(hbandplot, lbandplot, title="Channel Fill", color=color.new(fcolor, 80))
barcolor(barcolor)

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
// Trading Logic - long only
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
gaussianGreen = filt > filt[1]
gaussianRed   = filt < filt[1]

// Enter only on the first green bar after a red bar.
greenFlip = gaussianGreen and gaussianRed[1]

// Exit only on the first red bar after a green bar.
redFlip = gaussianRed and gaussianGreen[1]

if greenFlip and timeCondition and strategy.position_size == 0
    strategy.entry("long", strategy.long)

if redFlip and strategy.position_size > 0
    strategy.close("long")
